index:
    pattern: /
    options:
        _controller: web\main::null
        _title: Главная страница
        _action: read
    methods: GET

page:
    prefix: /page
    resource: page.yml
block:
    prefix: /block
    resource: block.yml
user:
    prefix: /user
    resource: user.yml
role:
    prefix: /role
    resource: role.yml
setting:
    prefix: /setting
    resource: setting.yml
log:
    prefix: /log
    resource: log.yml
search:
    prefix: /search
    resource: search.yml